#!/usr/bin/env node

var webpack = require("webpack");
var WebpackDevServer = require("webpack-dev-server");
var config = require("../webpack.config");

var PORT = process.env.WEBPACK_PORT || 3001;
var HOST = process.env.WEBPACK_HOST || "localhost";

var compiler = webpack(config);
var opts = {
  hot: true,
  quiet: false,
  noInfo: true,
  publicPath: config.output.publicPath,
  stats: {
    colors: true
  },
};

var server = new WebpackDevServer(compiler, opts);
server.listen(PORT, HOST, function() {
  console.log("WebpackDevServer listening on http://" + HOST + ":" + PORT + ".");
});
