#!/usr/bin/env babel-node --stage 0

import gaze from 'gaze';
import path from 'path';
import {spawn} from 'child_process';
import {green, yellow} from 'colors';

const ROOT = path.join(__dirname, '..');
const JS = path.join('**', '*.js');
const dirs = [
  path.join(ROOT, 'src', JS),
  path.join(ROOT, 'data', JS),
  path.join(ROOT, 'test', JS),
];

const lint = (event, pathname) => {
  process.stdout.write(yellow('Linting...\n'));
  const linter = spawn('./scripts/lint', [], {stdio: 'inherit'});

  if (linter.stdout) {
    linter.stdout.on('data', process.stdout.write);
  }

  if (linter.stderr) {
    linter.stderr.on('data', process.stderr.write);
  }

  linter.on('exit', (code) => {
    if (code === 0) {
      process.stdout.write(green('✓ 0 problems (0 errors, 0 warnings)\n'));
    }
  });
};

gaze(dirs, function() {
  lint();
  this.on('all', lint);
});
