#!/usr/bin/env node_modules/.bin/babel-node --stage=0

import fs from 'fs';
import path from 'path';
import {graphql} from 'graphql';
import {introspectionQuery} from 'graphql/utilities';
import {Schema} from '../data/schema';

(async () => {
  let result = await graphql(Schema, introspectionQuery);

  if (result.errors) {
    console.error(`Error: ${JSON.stringify(result.errors, null, 2)}`);
  } else {
    const target = path.join(__dirname, '..', 'build', 'schema.json');
    fs.writeFileSync(target, JSON.stringify(result, null, 2));
  }
})();
